///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest_Example
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest_ExampleRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("d87474bf-0a3b-47f0-be39-39ea5fb0c60e")]
    public partial class MyTest_ExampleRepository : RepoGenBaseFolder
    {
        static MyTest_ExampleRepository instance = new MyTest_ExampleRepository();
        MyTest_ExampleRepositoryFolders.NewAppFolderAppFolder _newappfolder;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest_ExampleRepository element repository.
        /// </summary>
        [RepositoryFolder("d87474bf-0a3b-47f0-be39-39ea5fb0c60e")]
        public static MyTest_ExampleRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest_ExampleRepository() 
            : base("MyTest_ExampleRepository", "/", null, 0, false, "d87474bf-0a3b-47f0-be39-39ea5fb0c60e", ".\\RepositoryImages\\MyTest_ExampleRepositoryd87474bf.rximgres")
        {
            _newappfolder = new MyTest_ExampleRepositoryFolders.NewAppFolderAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("d87474bf-0a3b-47f0-be39-39ea5fb0c60e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The NewAppFolder folder.
        /// </summary>
        [RepositoryFolder("d1d4eaf8-d5e7-4589-a819-3a064aae1799")]
        public virtual MyTest_ExampleRepositoryFolders.NewAppFolderAppFolder NewAppFolder
        {
            get { return _newappfolder; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class MyTest_ExampleRepositoryFolders
    {
        /// <summary>
        /// The NewAppFolderAppFolder folder.
        /// </summary>
        [RepositoryFolder("d1d4eaf8-d5e7-4589-a819-3a064aae1799")]
        public partial class NewAppFolderAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new NewAppFolder  folder.
            /// </summary>
            public NewAppFolderAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NewAppFolder", "/desktop[@processname='explorer']", parentFolder, 30000, null, true, "d1d4eaf8-d5e7-4589-a819-3a064aae1799", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d1d4eaf8-d5e7-4589-a819-3a064aae1799")]
            public virtual Ranorex.Desktop Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Desktop>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d1d4eaf8-d5e7-4589-a819-3a064aae1799")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}