///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AnotherTestProject
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AnotherTestProjectRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    [RepositoryFolder("5c3458b5-3075-4803-b4af-7894b6688f43")]
    public partial class AnotherTestProjectRepository : RepoGenBaseFolder
    {
        static AnotherTestProjectRepository instance = new AnotherTestProjectRepository();

        /// <summary>
        /// Gets the singleton class instance representing the AnotherTestProjectRepository element repository.
        /// </summary>
        [RepositoryFolder("5c3458b5-3075-4803-b4af-7894b6688f43")]
        public static AnotherTestProjectRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AnotherTestProjectRepository() 
            : base("AnotherTestProjectRepository", "/", null, 0, false, "5c3458b5-3075-4803-b4af-7894b6688f43", ".\\RepositoryImages\\AnotherTestProjectRepository5c3458b5.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("5c3458b5-3075-4803-b4af-7894b6688f43")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.3")]
    public partial class AnotherTestProjectRepositoryFolders
    {
    }
#pragma warning restore 0436
}